### ISSUE TITLE
[BUG] Task exception was never retrieved

### ISSUE THREAD

**Issue by ecsplendid** [xorbitsai/xoscar#121]

**Comment by ecsplendid** [comment]
```
Corrupt value: 0x56311111d22f64f3
python(30230,0x32b01f000) malloc: *** set a breakpoint in malloc_error_break to debug
```

New error not seen before on 0.4.6

**Comment by ecsplendid** [comment]
Got a slightly better error now after reverting to 0.4.3

```
zsh: segmentation fault  python ...
socket.send() raised exception.                                                                                                   
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
Task exception was never retrieved
future: <Task finished name='Task-26' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timTask exception was never retrieved
future: <Task finished name='Task-22' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timTask exception was never retrieved
future: <Task finished name='Task-22' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
scarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
scarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
Task exception was never retrieved
future: <Task finished name='Task-29' coro=<AbstractActorPool.process_message() done, defined at /Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py:410> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 426, in process_message
    await self._send_channel(processor.result, channel)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/pool.py", line 378, in _send_channel
    await channel.send(result)
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/site-packages/xoscar/backends/communication/socket.py", line 88, in send
    await self.writer.drain()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/Users/timscarfe/miniconda3/envs/xoscar_env/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
```

For some reason its now dying every time, not seen this before
